---
title: ' '
pagetitle: Daniele Giardiello
---


<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">


### About me
I am a statistician who conducts research in statistical methods for health services research and clinical epidemiological research. I conduct research in the following four areas: (1) statistical and machine learning methods for predicting patient outcomes; (2) survival analysis; (3) methods for clustered data; (4) methods for dynamic predictions. I also have extensive experience in the analysis of large administrative healthcare databases. I am also interested in causal inference methods. 

This website contains my (current) general and specific research interests and a collection of my work such as selected [publications](https://danielegiardiello.github.io/research.html) and my contributions to methodological developments in medical statistics, especially as a [programmer](https://danielegiardiello.github.io/programming.html).   

More details can be found at [GitHub](https://github.com/danielegiardiello) and [Google Scholar](https://scholar.google.com/citations?hl=en&user=6Xro0z8AAAAJ&view_op=list_works&sortby=pubdate).  

#### Brief CV

+ 2024 - present: assistant professor in medical statistics at University of Milan-Bicocca;

+ 2023: experiences as statistician in industries working in clinical trials and AI for imaging analyses (Chiesi & Menarini);  

+ 2021-2022: biostatistician at EURAC Research (Italy);  

+ 2016-2021: PhD candidate at the Netherlands Cancer Institute and Leiden University Medical Center (Amsterdam, the Netherlands);   

+ 2014-2016: Biostatistician at the Italian National Cancer Institute (Milan, Italy);  

+ 2013-2014: Statistician at Zooprophylactic Institute of Lombardy and Emilia-Romagna (Brescia, Italy);  


##### Education

+ 2022: PhD from [Leiden University](https://www.universiteitleiden.nl/en). PhD dissertation _"Prediction of contralateral breast cancer - Statistical aspects and performance assessment"_  is available [here](https://books.gildeprint.nl/thesis/579953-Giardiello/) and also available through Leiden University website [here](https://scholarlypublications.universiteitleiden.nl/handle/1887/3455362).

+ 2012: Master of Science (MSc) degree in Biostatistics and Experimental Statistics from [University of Milan-Bicocca](https://en.unimib.it/);   

+ 2010: Bachelor degree (BSc) in Statistics and Information management from [University of Milan-Bicocca](https://en.unimib.it/).  









