---
title: " "
pagetitle: "Daniele Giardiello"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">


### Github repositories

- [`Prediction_performance_survival`](https://github.com/danielegiardiello/Prediction_performance_survival) (author). R, SAS and Python code repository for the manuscript ['Assessing performance and clinical usefulness in prediction models with survival outcomes: practical guidance for Cox proportional hazards models'](https://www.acpjournals.org/doi/10.7326/M22-0844).  

- [`ValidationCompRisks`](https://github.com/survival-lumc/ValidationCompRisks) (author of .Rmd files/maintainer), R code repository for the manuscript ['Validation of prediction models in presence of competing risks: a guide through modern methods'](https://www.bmj.com/content/377/bmj-2021-069249.abstract).  
- [`ValLogRegMod`](https://github.com/danielegiardiello/ValLogRegMod) (author), R and Python code repository for the manuscript ['Assessing the performance of prediction models: a framework for some traditional and novel measures'](https://pubmed.ncbi.nlm.nih.gov/20010215/). The repository provides guidance about how to develop and validate a risk prediction model for binary outcomes using logistic regression including more recent updates about performance assessment.  

- [`ClusterSurvPred`](https://github.com/danielegiardiello/ClusterSurvPred) (author) R repository for the pre-print manuscript ['The impact of the number and the size of clusters on prediction performance of the stratified and the conditional shared gamma frailty Cox proportional hazards models'](https://pubmed.ncbi.nlm.nih.gov/41378355/). The repository provides R functions and code to evaluate conditional predictions from the frailty shared gamma and the stratified Cox proportional hazards models also using practical examples.  


### CRAN packages
- [`raters`](https://cran.r-project.org/web/packages/raters/index.html) (creator), a package of functions to assess the reliability of agreement among multiple observers. A Modification of Fleiss' Kappa in Case of Nominal and Ordinal Variables is proposed.  

